### PR TITLE
Grad schedule + credit

### PR DESCRIPTION
**Pull request by JoelGritter**
- uploading my grad schedule spreadsheet
- giving me credit LOL

### CODE REVIEW

**Comment by JoelGritter** [comment]
Also @kindeep is there a better way to store + link to files than directly in the repo assets?

**Comment by kindeep** [comment]
@JoelGritter the assets folder is for static assets for the angular website, can't think of a better way, at least right now.

**Comment by kindeep** [comment]
@JoelGritter We can build out or use some prebuilt firebase cms, but probably super unnecessary for our purpose, we could host it on a different repo though just on github pages. Open to ideas of course.

**Comment by kindeep** [comment]
For dynamic assets though, we can use firebase storage, that's how the event files and exec images are stored

**Review by kindeep — APPROVED** [review]

**Pull request merged**
